name: win32
description: A Dart library for accessing common Win32 APIs using FFI. No C required!
version: 1.6.8
homepage: https://timsneath.github.io/win32/
repository: https://github.com/timsneath/win32
issue_tracker: https://github.com/timsneath/win32/issues
documentation: https://timsneath.github.io/win32/

environment:
  sdk: '>=2.9.0-20 <2.10.0'

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2